name: Deploy to Faable
on:
  push:
    branches:
      - main
env:
  FAABLE_APIKEY: ${{ secrets.FAABLE_APIKEY }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare CLI
        run: npm i -g @faable/faable
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: yarn
      - run: yarn install --frozen-lockfile
      - name: Deploy to Faable
        run: faable deploy brand
